from typing import Annotated, TypedDict, Annotated
import operator

from pydantic import BaseModel, Field

# individual workers will be handed each of the tasks to complete 
class Task(BaseModel):
    id: int = Field(..., description="The id of the task")
    title: str = Field(..., description="The title of the task")
    description: str = Field(..., description="The description of the task and what points to cover in this task")
    goal: str = Field(
        ...,
        description="One sentence describing what the reader should be able to do/understand after this section.",
    )
    bullets: list[str] = Field(
        ...,
        min_length=3,
        max_length=5,
        description="3–5 concrete, non-overlapping subpoints to cover in this section.",
    )
    target_words: int = Field(
        ...,
        description="Target word count for this section (120–450).",
    )



# this is the plan generated by the orchestrator for writing blogs
class Plan(BaseModel):
    blog_title: str = Field(..., description="The title of the blog")
    blog_description: str = Field(..., description="The description of the blog")
    tasks: list[Task] = Field(..., description="The tasks to complete to write the blog")
    audience: str = Field(..., description="Who this blog is for.")

class BlogState(TypedDict):
    plan: Plan
    topic: str
    sections: Annotated[list[str], operator.add]
    final_blog: str
