from typing import Annotated, TypedDict, Annotated
import operator

from pydantic import BaseModel, Field

# individual workers will be handed each of the tasks to complete 
class Task(BaseModel):
    id: int = Field(..., description="The id of the task")
    title: str = Field(..., description="The title of the task")
    description: str = Field(..., description="The description of the task and what points to cover in this task")

# this is the plan generated by the orchestrator for writing blogs
class Plan(BaseModel):
    blog_title: str = Field(..., description="The title of the blog")
    blog_description: str = Field(..., description="The description of the blog")
    tasks: list[Task] = Field(..., description="The tasks to complete to write the blog")

class BlogState(TypedDict):
    plan: Plan
    topic: str
    sections: Annotated[list[str], operator.add]
    final_blog: str
